version: "{build}"

clone_depth: 1

install:
- ps: >-
    $name = Select-String -Path nfive.yml -Pattern 'name: ?(.+)$' | %{ $_.Matches[0].Groups[1].Value }

    If ($env:APPVEYOR_REPO_PROVIDER -eq "github" -and $env:APPVEYOR_REPO_NAME -ne $name) {
      Add-AppveyorMessage -Message "Plugin name mismatch" -Category Error -Details "The GitHub repo name '$env:APPVEYOR_REPO_NAME' does not match the plugin name '$name' from nfive.yml."
      Write-Host "Plugin name mismatch: The GitHub repo name '$env:APPVEYOR_REPO_NAME' does not match the plugin name '$name' from nfive.yml." -ForegroundColor Red
      $host.SetShouldExit(1)
    }

    $env:BUILD_VERSION = Select-String -Path nfive.yml -Pattern 'version: ?(.+)$' | %{ $_.Matches[0].Groups[1].Value }

    If ($env:APPVEYOR_REPO_TAG -eq $true) {
      $tag = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v")

      If ($tag -ne $env:BUILD_VERSION) {
        Add-AppveyorMessage -Message "Plugin version mismatch" -Category Error -Details "The Git tag '$tag' does not match the plugin version number '$env:BUILD_VERSION' from nfive.yml."
        Write-Host "Plugin version mismatch: The Git tag '$tag' does not match the plugin version number '$env:BUILD_VERSION' from nfive.yml." -ForegroundColor Red
        $host.SetShouldExit(1)
      }
    }

    $env:BUILD_VERSION_FILE = "$env:BUILD_VERSION.$env:APPVEYOR_BUILD_NUMBER"

    $version = $env:BUILD_VERSION -split '-'

    If ($version[1]) {
      $env:BUILD_VERSION_FILE = "$($version[0]).$env:APPVEYOR_BUILD_NUMBER-$($version[1])"
    }

    Update-AppveyorBuild -Version $env:BUILD_VERSION_FILE

build: off

after_build:
- ps: 7z a "$($env:APPVEYOR_PROJECT_NAME).zip" src/* nfive.yml README.md LICENSE

artifacts:
- path: $(APPVEYOR_PROJECT_NAME).zip

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: 11Aj9GejhzBxJlpQAwmcgJKINliGVNQ/mWTTFZCylmKiwglzys7hWxRZiRfT7INp
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
